# docker-compose.yml
version: "3.3"
services:
    butler-sos:
        image: ptarmiganlabs/butler-sos:9.3.1
        container_name: butler-sos
        restart: always
        volumes:
            # Make config file and log files accessible outside of container
            - ./config:/nodeapp/config
            - ./log:/nodeapp/log
        ports:
            - 9997:9997/udp             # User events from Sense
            - 9996:9996/udp             # Log events from Sense
        environment:
            - NODE_ENV=production  # Means that Butler SOS will read config data from production.yaml
        logging:
            driver: "json-file"
            options:
                max-file: "5"
                max-size: "5m"
        networks:
            - senseops

    influxdb:
        image: influxdb:1.8.10
        container_name: influxdb
        restart: always
        volumes:
            - ./influxdb/data:/var/lib/influxdb # Mount for influxdb data directory
            - ./influxdb/config/:/etc/influxdb/ # Mount for influxdb configuration
        ports:
            # The API for InfluxDB is served on port 8086
            - 8086:8086
            - 8082:8082
        environment:
            # Disable usage reporting
            - INFLUXDB_REPORTING_DISABLED=true
        networks:
            - senseops

    grafana:
        image: grafana/grafana:9.1.0
        container_name: grafana
        restart: always
        ports:
            - 3000:3000
        volumes:
            - ./grafana/data:/var/lib/grafana
        environment:
            - GF_INSTALL_PLUGINS=grafana-clock-panel
        networks:
            - senseops

networks:
    senseops:
        driver: bridge
